address=/api-preprod.amazon.com/10.201.126.241
address=/api.amazon.com/10.201.126.241
address=/api.integ.amazon.com/10.201.126.241
address=/guipitan.amazon.ca/10.201.126.241
address=/guipitan.amazon.cn/10.201.126.241
address=/guipitan.amazon.co.jp/10.201.126.241
address=/guipitan.amazon.com.au/10.201.126.241
address=/guipitan.amazon.com.br/10.201.126.241
address=/guipitan.amazon.com.mx/10.201.126.241
address=/guipitan.amazon.com/10.201.126.241
address=/guipitan.amazon.fr/10.201.126.241
address=/guipitan.amazon.in/10.201.126.241
address=/guipitan.amazon.it/10.201.126.241
address=/guipitan.amazon.nl/10.201.126.241
address=/ilaw-proxy.pdx.corp.amazon.com/10.201.126.241
address=/penny-rms-alpha.integ.amazon.com/10.201.126.241
address=/penny-rms-beta.integ.amazon.com/10.201.126.241
address=/penny-rms-gamma.us-east-1.amazonaws.com/10.201.126.241
address=/penny-rms-prod.us-east-1.amazonaws.com/10.201.126.241
address=/projectdee-ui-au-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-br-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-ca-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-cn-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-de-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-dev-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-eu-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-fr-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-gb-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-in-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-it-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-jp-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-mx-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-nl-registration.aka.amazon.com/10.201.126.241
address=/projectdee-ui-registration.aka.amazon.com/10.201.126.241
address=/seamus.amazon.co.uk/10.201.126.241
address=/seamus.amazon.com/10.201.126.241
address=/seamus.amazon.de/10.201.126.241
address=/dss-na.amazon.com/10.201.126.241
address=/dss-eu.amazon.com/10.201.126.241
address=/dss-jp.amazon.com/10.201.126.241
address=/dp-sps-na.amazon.com/10.201.126.241
address=/dp-sps-eu.amazon.com/10.201.126.241
address=/dp-sps-jp.amazon.com/10.201.126.241
bind-interfaces
dhcp-range=10.201.126.242,10.201.126.254,20m
listen-address=10.201.126.241
