# Update Engine wait logic
TIME_TO_FORCE_UPDATE=86400
UPDATE_BACKOFF_MAX_SECONDS=900
REBOOT_IDLE_SECONDS_ACCELERATED=300
MAX_NUM_DOWNLOAD_RETRIES=10

# OTA timeout values
OTA_UPDATE_TIMED_OUT_SECONDS=3600
DAY0_OTA_PAUSE_SECONDS=60
VUI_OTA_PAUSE_SECONDS=300
